/* The following code was generated by JFlex 1.4.3 on 3/24/10 12:23 AM */

package yeungda.coffeescript.lang;


import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/24/10 12:23 AM from the specification file
 * <tt>/Users/dyeung/Projects/coffeescript/src/yeungda/coffeescript/lang/lexer.flex</tt>
 */
class Lexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int SINGLE_QUOTE_STRING = 4;
  public static final int YYINITIAL = 0;
  public static final int DOUBLE_QUOTE_STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\16\1\17\2\0\1\1\22\0\1\16\1\15\1\21\1\20"+
    "\1\2\2\15\1\22\1\53\1\53\1\15\1\12\1\56\1\12\1\10"+
    "\1\15\1\4\11\3\1\15\1\55\1\15\1\15\1\15\1\15\1\13"+
    "\6\7\11\2\1\52\7\2\1\6\2\2\1\54\1\23\1\54\1\0"+
    "\1\51\1\0\1\40\1\43\1\37\1\45\1\11\1\27\1\50\1\41"+
    "\1\26\1\2\1\44\1\30\1\25\1\32\1\42\1\46\1\2\1\33"+
    "\1\31\1\34\1\35\1\47\1\14\1\5\1\36\1\2\1\24\1\15"+
    "\1\24\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\2\4\1\5\1\3\1\6"+
    "\1\7\1\3\1\2\1\10\1\11\1\12\1\13\20\3"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\1"+
    "\1\20\1\1\3\0\5\3\1\0\1\3\3\23\11\3"+
    "\1\24\12\3\1\23\1\24\2\3\1\25\3\3\1\26"+
    "\1\27\2\4\1\0\1\4\107\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\215\0\u0178\0\u01a7\0\215\0\u01d6\0\u0205\0\u0234\0\215"+
    "\0\215\0\215\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e"+
    "\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6"+
    "\0\u04f5\0\u0524\0\215\0\215\0\215\0\215\0\u0553\0\215"+
    "\0\215\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c"+
    "\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\353\0\u07e5"+
    "\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5"+
    "\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\353\0\u0c1e"+
    "\0\u0c4d\0\353\0\u0c7c\0\u0cab\0\u0cda\0\215\0\215\0\u0d09"+
    "\0\u0d38\0\u0d38\0\u066d\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23"+
    "\0\u0e52\0\u0e81\0\u09ea\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4"+
    "\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c"+
    "\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4"+
    "\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d\0\u154c"+
    "\0\u157b\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4"+
    "\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af\0\u17de\0\u180d\0\u183c"+
    "\0\u186b\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956\0\u1985\0\u19b4"+
    "\0\u19e3\0\u1a12";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\3\6\1\11\1\12"+
    "\1\13\1\14\1\15\1\13\2\16\1\17\1\20\1\21"+
    "\1\4\1\22\1\6\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\6\1\36"+
    "\1\37\1\6\1\40\1\6\1\41\1\6\1\42\1\6"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\15\47\1\50"+
    "\1\47\1\51\1\47\1\52\33\47\1\53\1\50\15\53"+
    "\1\50\2\53\1\51\1\54\33\53\60\0\1\5\14\0"+
    "\2\5\41\0\6\6\1\0\1\6\2\0\1\6\10\0"+
    "\26\6\7\0\2\7\3\0\1\55\1\56\50\0\2\7"+
    "\2\57\1\0\1\55\1\56\47\0\3\6\1\60\2\6"+
    "\1\0\1\6\2\0\1\6\10\0\3\6\1\61\1\6"+
    "\1\62\20\6\16\0\1\13\2\0\1\13\43\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\1\6\1\63\12\6"+
    "\1\64\11\6\5\0\1\5\14\0\1\16\1\5\1\17"+
    "\36\0\17\17\1\65\37\17\2\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\1\66\1\6\1\67\1\6\1\70"+
    "\1\71\20\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\1\6\1\72\6\6\1\73\2\6\1\74\1\6"+
    "\1\75\10\6\6\0\6\6\1\0\1\76\2\0\1\6"+
    "\10\0\26\6\6\0\6\6\1\0\1\6\2\0\1\77"+
    "\10\0\10\6\1\100\15\6\6\0\6\6\1\0\1\101"+
    "\2\0\1\6\10\0\13\6\1\102\1\6\1\103\10\6"+
    "\6\0\6\6\1\0\1\104\2\0\1\6\10\0\26\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\6\6"+
    "\1\105\2\6\1\106\2\6\1\107\11\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\5\6\1\110\20\6"+
    "\6\0\6\6\1\0\1\111\2\0\1\6\10\0\26\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\3\6"+
    "\1\112\7\6\1\113\1\6\1\114\10\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\5\6\1\115\20\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\2\6"+
    "\1\116\2\6\1\117\1\67\17\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\6\6\1\120\2\6\1\67"+
    "\14\6\6\0\6\6\1\0\1\121\2\0\1\6\10\0"+
    "\15\6\1\122\10\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\13\6\1\123\1\6\1\124\10\6\6\0"+
    "\6\6\1\0\1\6\2\0\1\6\10\0\24\6\1\125"+
    "\1\6\4\0\1\47\1\0\15\47\1\0\1\47\1\0"+
    "\1\47\1\0\33\47\17\126\1\0\1\126\1\127\1\126"+
    "\1\127\6\126\1\127\24\126\1\53\1\0\15\53\1\0"+
    "\2\53\2\0\33\53\17\126\1\0\2\126\2\127\6\126"+
    "\1\127\24\126\3\0\2\130\55\0\2\131\5\0\1\132"+
    "\47\0\2\133\2\0\1\133\1\0\1\133\15\0\1\133"+
    "\7\0\2\133\2\0\1\133\1\0\1\133\13\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\7\6\1\134\11\6"+
    "\1\135\4\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\4\6\1\136\21\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\10\6\1\137\15\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\7\6\1\140\16\6"+
    "\6\0\6\6\1\0\1\141\2\0\1\6\10\0\1\6"+
    "\1\142\24\6\22\0\1\65\1\0\1\17\40\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\21\6\1\135\4\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\5\6"+
    "\1\143\20\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\4\6\1\144\21\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\5\6\1\145\20\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\5\6\1\146\20\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\3\6"+
    "\1\147\22\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\6\6\1\67\17\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\7\6\1\122\16\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\1\6\1\150\24\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\21\6"+
    "\1\151\4\6\6\0\6\6\1\0\1\6\2\0\1\67"+
    "\10\0\26\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\7\6\1\152\16\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\7\6\1\67\16\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\7\6\1\153\16\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\10\6"+
    "\1\154\1\67\14\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\21\6\1\155\4\6\6\0\6\6\1\0"+
    "\1\156\2\0\1\6\10\0\6\6\1\157\17\6\6\0"+
    "\6\6\1\0\1\6\2\0\1\6\10\0\3\6\1\160"+
    "\22\6\6\0\6\6\1\0\1\6\2\0\1\6\10\0"+
    "\4\6\1\117\21\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\13\6\1\161\12\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\4\6\1\162\2\6\1\163"+
    "\16\6\6\0\6\6\1\0\1\6\2\0\1\6\10\0"+
    "\5\6\1\164\20\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\20\6\1\67\5\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\2\6\1\117\23\6\6\0"+
    "\6\6\1\0\1\165\2\0\1\6\10\0\26\6\6\0"+
    "\6\6\1\0\1\6\2\0\1\6\10\0\2\6\1\166"+
    "\1\167\12\6\1\170\7\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\6\6\1\122\17\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\1\6\1\171\24\6"+
    "\6\0\6\6\1\0\1\172\2\0\1\6\10\0\14\6"+
    "\1\173\11\6\7\0\2\130\4\0\1\56\50\0\2\131"+
    "\54\0\6\6\1\0\1\174\2\0\1\6\10\0\26\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\15\6"+
    "\1\175\10\6\6\0\6\6\1\0\1\67\2\0\1\6"+
    "\10\0\26\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\1\122\25\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\14\6\1\122\11\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\5\6\1\67\1\136\17\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\3\6"+
    "\1\136\22\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\7\6\1\176\16\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\13\6\1\177\12\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\12\6\1\200\13\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\4\6"+
    "\1\154\21\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\7\6\1\163\16\6\6\0\6\6\1\0\1\75"+
    "\2\0\1\6\10\0\26\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\1\6\1\201\24\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\10\6\1\202\15\6"+
    "\6\0\6\6\1\0\1\117\2\0\1\6\10\0\26\6"+
    "\6\0\6\6\1\0\1\203\2\0\1\6\10\0\26\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\5\6"+
    "\1\67\20\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\15\6\1\101\10\6\6\0\6\6\1\0\1\161"+
    "\2\0\1\6\10\0\26\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\4\6\1\204\21\6\6\0\6\6"+
    "\1\0\1\122\2\0\1\6\10\0\26\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\12\6\1\205\13\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\4\6"+
    "\1\76\2\6\1\206\16\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\13\6\1\207\12\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\13\6\1\210\12\6"+
    "\6\0\6\6\1\0\1\211\2\0\1\6\10\0\26\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\10\6"+
    "\1\212\15\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\20\6\1\122\5\6\6\0\3\6\1\213\2\6"+
    "\1\0\1\6\2\0\1\6\10\0\26\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\13\6\1\214\12\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\5\6"+
    "\1\215\20\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\6\6\1\76\17\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\13\6\1\216\12\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\3\6\1\217\22\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\7\6"+
    "\1\220\16\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\22\6\1\162\3\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\6\6\1\156\17\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\15\6\1\221\10\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\4\6"+
    "\1\67\21\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\14\6\1\67\11\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\1\6\1\222\24\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\17\6\1\67\6\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\10\6"+
    "\1\223\15\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\7\6\1\136\16\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\23\6\1\224\2\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\7\6\1\225\16\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\4\6"+
    "\1\226\21\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\20\6\1\204\5\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\5\6\1\227\20\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\3\6\1\230\22\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\1\6"+
    "\1\231\24\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\2\6\1\67\23\6\6\0\6\6\1\0\1\6"+
    "\2\0\1\6\10\0\5\6\1\232\20\6\6\0\6\6"+
    "\1\0\1\6\2\0\1\6\10\0\3\6\1\76\22\6"+
    "\6\0\6\6\1\0\1\6\2\0\1\6\10\0\23\6"+
    "\1\233\2\6\6\0\6\6\1\0\1\234\2\0\1\6"+
    "\10\0\26\6\6\0\6\6\1\0\1\6\2\0\1\6"+
    "\10\0\25\6\1\235\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\12\6\1\155\13\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\11\6\1\67\14\6\6\0"+
    "\6\6\1\0\1\6\2\0\1\6\10\0\15\6\1\236"+
    "\10\6\6\0\6\6\1\0\1\6\2\0\1\6\10\0"+
    "\10\6\1\136\15\6\6\0\6\6\1\0\1\123\2\0"+
    "\1\6\10\0\26\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\5\6\1\237\20\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\6\6\1\240\17\6\6\0"+
    "\6\6\1\0\1\6\2\0\1\6\10\0\5\6\1\122"+
    "\20\6\6\0\6\6\1\0\1\6\2\0\1\6\10\0"+
    "\20\6\1\241\5\6\6\0\6\6\1\0\1\6\2\0"+
    "\1\6\10\0\15\6\1\242\10\6\6\0\6\6\1\0"+
    "\1\6\2\0\1\6\10\0\4\6\1\122\21\6\6\0"+
    "\6\6\1\0\1\6\2\0\1\6\10\0\21\6\1\122"+
    "\4\6\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6721];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\1\11\2\1\1\11\3\1\3\11"+
    "\20\1\4\11\1\1\2\11\3\1\3\0\5\1\1\0"+
    "\40\1\2\11\2\1\1\0\110\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return Tokens.BOOLEAN;
          }
        case 24: break;
        case 10: 
          { yybegin(SINGLE_QUOTE_STRING); return Tokens.STRING;
          }
        case 25: break;
        case 4: 
          { return Tokens.NUMBER;
          }
        case 26: break;
        case 18: 
          { yybegin(YYINITIAL); return Tokens.STRING;
          }
        case 27: break;
        case 8: 
          { return Tokens.COMMENT;
          }
        case 28: break;
        case 13: 
          { return Tokens.BRACKET;
          }
        case 29: break;
        case 19: 
          { return Tokens.KEYWORD;
          }
        case 30: break;
        case 15: 
          { return Tokens.COMMA;
          }
        case 31: break;
        case 22: 
          { return Tokens.BAD_CHARACTER;
          }
        case 32: break;
        case 12: 
          { return Tokens.PARENTHESIS;
          }
        case 33: break;
        case 5: 
          { return Tokens.DOT;
          }
        case 34: break;
        case 2: 
          { return Tokens.WHITESPACE;
          }
        case 35: break;
        case 17: 
          { return Tokens.LINE_TERMINATOR;
          }
        case 36: break;
        case 3: 
          { return Tokens.IDENTIFIER;
          }
        case 37: break;
        case 6: 
          { return Tokens.OPERATOR;
          }
        case 38: break;
        case 1: 
          { yybegin(YYINITIAL);   return Tokens.BAD_CHARACTER;
          }
        case 39: break;
        case 21: 
          { return Tokens.RESERVED_WORD;
          }
        case 40: break;
        case 9: 
          { yybegin(DOUBLE_QUOTE_STRING); return Tokens.STRING;
          }
        case 41: break;
        case 7: 
          { return Tokens.ACCESSOR;
          }
        case 42: break;
        case 11: 
          { return Tokens.BRACE;
          }
        case 43: break;
        case 16: 
          { return Tokens.STRING;
          }
        case 44: break;
        case 23: 
          { return Tokens.STRING_LITERAL;
          }
        case 45: break;
        case 14: 
          { return Tokens.SEMI_COLON;
          }
        case 46: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
