/* The following code was generated by JFlex 1.4.3 on 3/29/10 8:50 PM */

package yeungda.coffeescript.lang;


import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/29/10 8:50 PM from the specification file
 * <tt>/Users/dyeung/Projects/coffeescript/src/yeungda/coffeescript/lang/lexer.flex</tt>
 */
class Lexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int REGULAR_EXPRESSION = 8;
  public static final int VERB = 10;
  public static final int REGULAR_EXPRESSION_FLAG = 12;
  public static final int HEREDOCS = 18;
  public static final int DOUBLE_QUOTE_STRING = 4;
  public static final int SINGLE_QUOTE_STRING = 6;
  public static final int YYINITIAL = 0;
  public static final int NOUN = 2;
  public static final int JAVASCRIPT = 16;
  public static final int NOUN_OR_VERB = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9, 9
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\20\2\0\1\27\22\0\1\1\1\15\1\24\1\21"+
    "\1\2\1\62\1\63\1\25\1\70\1\66\1\62\1\16\1\67\1\12"+
    "\1\10\1\30\1\4\11\3\1\23\1\61\1\65\1\17\1\22\1\62"+
    "\1\13\6\7\11\2\1\60\7\2\1\6\2\2\1\71\1\26\1\72"+
    "\1\0\1\57\1\34\1\36\1\53\1\35\1\40\1\11\1\41\1\54"+
    "\1\52\1\47\1\2\1\73\1\43\1\55\1\46\1\45\1\56\1\2"+
    "\1\51\1\37\1\44\1\42\1\50\1\14\1\5\1\33\1\2\1\31"+
    "\1\64\1\32\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\3\0\1\2\1\3\1\4\2\5\1\4"+
    "\1\6\1\7\1\4\1\6\1\2\1\10\1\11\1\12"+
    "\1\13\1\10\1\14\1\15\1\4\1\16\17\4\1\17"+
    "\2\2\1\20\1\21\1\22\1\23\2\4\1\24\2\25"+
    "\1\26\5\4\1\27\1\30\1\2\1\27\1\2\1\31"+
    "\1\32\1\2\1\33\1\34\1\2\3\6\2\35\7\2"+
    "\3\6\1\36\1\37\1\1\2\4\1\40\1\41\2\42"+
    "\3\0\3\4\1\43\2\4\2\0\10\4\1\44\11\4"+
    "\1\45\1\46\1\45\3\4\1\46\1\45\13\4\1\47"+
    "\1\50\1\51\1\33\1\6\5\0\1\45\1\0\1\45"+
    "\1\1\1\4\1\45\1\0\2\5\1\0\1\5\7\4"+
    "\1\52\32\4\1\33\3\0\1\1\1\4\1\53\13\4"+
    "\1\54\6\4\1\33\1\0\1\1\12\4\1\33\1\0"+
    "\14\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[253];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\u012c\0\u0168\0\u01a4"+
    "\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348\0\u0384"+
    "\0\u03c0\0\u0258\0\u03fc\0\u0258\0\u03c0\0\u0438\0\u0474\0\u0258"+
    "\0\u04b0\0\u0258\0\u0258\0\u0258\0\u04ec\0\u0258\0\u0528\0\u0564"+
    "\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\u06cc\0\u0708\0\u0744"+
    "\0\u0780\0\u07bc\0\u07f8\0\u0834\0\u0870\0\u0258\0\u08ac\0\u08e8"+
    "\0\u0258\0\u0258\0\u0258\0\u0258\0\u0924\0\u0960\0\u03c0\0\u0438"+
    "\0\u0258\0\u0258\0\u099c\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8"+
    "\0\u0258\0\u0b04\0\u0b40\0\u0b7c\0\u0bb8\0\u0258\0\u0bf4\0\u0c30"+
    "\0\u0c6c\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10"+
    "\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u0f3c\0\u0f78\0\u08ac\0\u08e8"+
    "\0\u0fb4\0\u0258\0\u0258\0\u0ff0\0\u102c\0\u1068\0\u10a4\0\u0258"+
    "\0\u0258\0\u10e0\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248"+
    "\0\u0258\0\u1284\0\u12c0\0\u0438\0\u12fc\0\u1338\0\u1374\0\u13b0"+
    "\0\u13ec\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u02d0\0\u1518\0\u1554"+
    "\0\u1590\0\u15cc\0\u1608\0\u1644\0\u1680\0\u16bc\0\u16f8\0\u1734"+
    "\0\u02d0\0\u02d0\0\u1770\0\u17ac\0\u17e8\0\u1824\0\u1860\0\u189c"+
    "\0\u18d8\0\u1914\0\u1950\0\u198c\0\u19c8\0\u1a04\0\u1a40\0\u1a7c"+
    "\0\u1ab8\0\u1af4\0\u0258\0\u0258\0\u0258\0\u1b30\0\u1b6c\0\u1ba8"+
    "\0\u1be4\0\u0f00\0\u1c20\0\u1c5c\0\u0258\0\u1c98\0\u1cd4\0\u1d10"+
    "\0\u1d4c\0\u189c\0\u1d88\0\u1dc4\0\u1e00\0\u1e00\0\u1194\0\u1e3c"+
    "\0\u1e78\0\u1eb4\0\u1ef0\0\u1f2c\0\u1f68\0\u1fa4\0\u0258\0\u1fe0"+
    "\0\u201c\0\u2058\0\u2094\0\u20d0\0\u210c\0\u2148\0\u2184\0\u21c0"+
    "\0\u21fc\0\u2238\0\u2274\0\u22b0\0\u22ec\0\u2328\0\u2364\0\u23a0"+
    "\0\u23dc\0\u1824\0\u2418\0\u2454\0\u2490\0\u24cc\0\u2508\0\u2544"+
    "\0\u2580\0\u25bc\0\u25f8\0\u2634\0\u2670\0\u26ac\0\u26e8\0\u0258"+
    "\0\u2724\0\u2760\0\u279c\0\u27d8\0\u2814\0\u2850\0\u288c\0\u28c8"+
    "\0\u2904\0\u2940\0\u297c\0\u02d0\0\u29b8\0\u29f4\0\u2a30\0\u2a6c"+
    "\0\u2aa8\0\u2ae4\0\u2b20\0\u2b5c\0\u0258\0\u2b98\0\u2bd4\0\u2c10"+
    "\0\u2c4c\0\u2c88\0\u2cc4\0\u2d00\0\u2d3c\0\u2d78\0\u2db4\0\u0258"+
    "\0\u2df0\0\u2e2c\0\u2e68\0\u2ea4\0\u2ee0\0\u2f1c\0\u2f58\0\u2f94"+
    "\0\u2fd0\0\u300c\0\u3048\0\u3084\0\u30c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[253];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\13\1\14\1\15\1\16\1\17\3\15\1\13\1\20"+
    "\1\21\1\22\1\23\1\13\1\24\1\25\1\26\1\27"+
    "\2\13\1\30\1\31\1\13\1\32\1\13\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\15"+
    "\1\54\3\15\1\55\1\15\1\56\1\24\1\57\1\60"+
    "\1\13\1\61\1\13\1\62\1\63\1\64\1\15\1\13"+
    "\1\14\1\15\1\16\1\17\3\15\1\13\1\65\1\21"+
    "\1\22\1\66\1\13\1\24\1\67\1\70\1\27\2\13"+
    "\1\30\1\31\1\13\1\71\1\72\1\33\1\34\1\35"+
    "\1\13\1\73\1\40\1\41\1\74\1\75\1\44\1\15"+
    "\1\46\1\47\1\76\1\77\1\15\1\53\1\15\1\54"+
    "\5\15\1\13\1\24\1\57\1\60\1\13\1\61\1\13"+
    "\1\62\1\63\1\64\1\15\20\100\1\32\3\100\1\101"+
    "\1\100\1\102\1\32\44\100\20\103\1\32\4\103\1\101"+
    "\1\104\1\32\44\103\20\105\1\106\5\105\1\107\1\106"+
    "\1\110\43\105\1\13\1\14\6\13\1\111\1\112\1\113"+
    "\1\22\1\13\1\114\1\115\1\116\1\70\1\27\1\114"+
    "\1\117\3\13\1\71\1\24\5\13\1\120\2\13\1\121"+
    "\1\122\1\13\1\123\1\124\1\125\1\126\12\13\1\24"+
    "\1\127\1\130\1\131\1\132\1\133\1\62\1\63\1\64"+
    "\21\13\1\0\12\13\1\134\13\13\1\134\4\13\2\134"+
    "\17\13\1\14\1\15\1\16\1\17\3\15\1\111\1\65"+
    "\1\113\1\22\1\66\1\114\1\115\1\116\1\70\1\27"+
    "\1\114\1\117\1\30\1\31\1\13\1\71\1\24\1\33"+
    "\1\34\1\35\1\13\1\73\1\40\1\41\1\74\1\75"+
    "\1\44\1\15\1\135\1\47\1\76\1\136\1\15\1\53"+
    "\1\15\1\54\5\15\1\13\1\24\1\127\1\130\1\131"+
    "\1\132\1\133\1\62\1\63\1\64\1\15\34\137\1\140"+
    "\37\137\20\141\1\32\4\141\1\142\1\141\1\32\44\141"+
    "\75\0\1\14\17\0\1\27\54\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\24\15\12\0\1\15"+
    "\3\0\2\16\3\0\1\143\1\144\65\0\2\16\2\145"+
    "\1\0\1\143\1\144\64\0\3\15\1\146\2\15\1\0"+
    "\1\15\2\0\1\15\16\0\1\15\1\0\6\15\1\147"+
    "\2\15\1\150\12\15\12\0\1\15\22\0\1\151\53\0"+
    "\6\15\1\0\1\15\2\0\1\15\16\0\1\15\1\0"+
    "\12\15\1\152\2\15\1\153\6\15\12\0\1\15\1\0"+
    "\1\154\17\0\1\27\52\0\20\27\1\154\53\27\25\0"+
    "\1\155\50\0\6\15\1\0\1\156\2\0\1\15\16\0"+
    "\1\15\1\0\24\15\12\0\1\15\2\0\6\15\1\0"+
    "\1\15\2\0\1\15\16\0\1\15\1\0\1\15\1\157"+
    "\4\15\1\160\1\15\1\161\13\15\12\0\1\15\2\0"+
    "\6\15\1\0\1\15\2\0\1\15\16\0\1\15\1\0"+
    "\11\15\1\162\12\15\12\0\1\15\2\0\6\15\1\0"+
    "\1\15\2\0\1\163\16\0\1\15\1\0\5\15\1\164"+
    "\16\15\12\0\1\15\2\0\6\15\1\0\1\165\2\0"+
    "\1\15\16\0\1\15\1\0\10\15\1\166\13\15\12\0"+
    "\1\15\2\0\6\15\1\0\1\15\2\0\1\15\16\0"+
    "\1\15\1\0\1\15\1\167\3\15\1\170\2\15\1\171"+
    "\1\15\1\172\11\15\12\0\1\15\2\0\6\15\1\0"+
    "\1\15\2\0\1\15\16\0\1\15\1\0\11\15\1\173"+
    "\12\15\12\0\1\15\2\0\6\15\1\0\1\174\2\0"+
    "\1\15\16\0\1\15\1\0\24\15\12\0\1\15\2\0"+
    "\6\15\1\0\1\15\2\0\1\15\16\0\1\175\1\0"+
    "\14\15\1\176\1\177\6\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\4\15"+
    "\1\200\4\15\1\201\2\15\1\202\7\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\203\2\0\1\15\16\0\1\15"+
    "\1\0\1\15\1\204\3\15\1\205\2\15\1\206\13\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\2\15\1\207\1\15\1\202\4\15"+
    "\1\210\6\15\1\211\3\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\1\15"+
    "\1\212\6\15\1\213\13\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\214\2\0\1\15\16\0\1\15\1\0\24\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\202\1\0\14\15\1\215\7\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\22\15\1\216\1\15\12\0\1\15\63\0\1\24"+
    "\74\0\1\24\11\0\3\15\1\217\2\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\6\15\1\147\15\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\15\15\1\153\6\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\1\15\1\220\4\15\1\160\1\15\1\221\13\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\222\2\0\1\15"+
    "\16\0\1\15\1\0\24\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\1\15"+
    "\1\167\6\15\1\171\1\15\1\172\11\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\203\2\0\1\15\16\0\1\15"+
    "\1\0\5\15\1\205\2\15\1\206\13\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\2\15\1\207\1\15\1\202\4\15\1\210\12\15"+
    "\12\0\1\15\20\100\1\0\3\100\1\0\1\100\2\0"+
    "\44\100\20\223\1\0\3\223\1\224\1\223\1\224\17\223"+
    "\1\224\25\223\20\103\1\0\4\103\3\0\44\103\20\223"+
    "\1\0\4\223\2\224\17\223\1\224\25\223\20\105\1\0"+
    "\5\105\3\0\43\105\20\225\1\0\53\225\33\0\1\226"+
    "\13\0\1\226\4\0\2\226\26\0\1\227\126\0\1\230"+
    "\42\0\1\24\7\0\1\151\70\0\1\24\72\0\1\24"+
    "\74\0\1\24\2\0\1\151\74\0\1\24\116\0\1\231"+
    "\72\0\1\232\74\0\1\233\77\0\1\234\72\0\1\235"+
    "\67\0\1\236\65\0\1\237\1\0\1\235\4\0\1\235"+
    "\37\0\1\24\4\0\1\24\107\0\1\240\13\0\1\240"+
    "\4\0\2\240\20\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\175\1\0\14\15\1\176\1\241\6\15\12\0"+
    "\1\15\2\0\6\15\1\0\1\15\2\0\1\15\16\0"+
    "\1\15\1\0\2\15\1\207\1\15\1\202\4\15\1\242"+
    "\12\15\12\0\1\15\34\137\1\0\37\137\25\0\1\243"+
    "\51\0\2\244\72\0\2\245\5\0\1\246\3\0\1\246"+
    "\60\0\2\247\2\0\1\247\1\0\1\247\23\0\2\247"+
    "\1\0\2\247\11\0\1\247\22\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\7\15\1\250\11\15"+
    "\1\251\2\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\2\15\1\252\21\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\5\15\1\253\16\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\7\15\1\254\14\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\255\2\0\1\15\16\0\1\15\1\0\12\15"+
    "\1\256\11\15\12\0\1\15\25\0\1\257\50\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\2\15"+
    "\1\201\21\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\2\15\1\260\4\15"+
    "\1\261\14\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\1\15\1\262\22\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\11\15\1\263\12\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\3\15\1\202\20\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\12\15"+
    "\1\220\11\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\21\15\1\264\2\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\4\15\1\265\1\15\1\266\7\15"+
    "\1\267\5\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\6\15\1\270\15\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\11\15\1\271\12\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\14\15\1\202\7\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\11\15"+
    "\1\272\12\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\6\15\1\273\15\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\7\15\1\166\14\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\21\15\1\274\2\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\202\1\0\5\15"+
    "\1\275\16\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\12\15\1\276\1\15"+
    "\1\277\7\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\4\15\1\201\17\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\202"+
    "\16\0\1\15\1\0\24\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\7\15"+
    "\1\300\14\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\6\15\1\301\15\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\7\15\1\202\14\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\11\15\1\302\12\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\2\15"+
    "\1\303\21\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\21\15\1\251\2\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\14\15\1\166\7\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\12\15\1\304\11\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\7\15"+
    "\1\305\14\15\12\0\1\15\2\0\6\15\1\0\1\306"+
    "\2\0\1\15\16\0\1\15\1\0\24\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\307\2\0\1\15\16\0\1\15"+
    "\1\0\15\15\1\310\6\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\7\15"+
    "\1\250\14\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\7\15\1\261\14\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\11\15\1\311\12\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\6\15\1\266\15\15\12\0\1\15\33\0\1\312"+
    "\13\0\1\312\4\0\2\312\26\0\1\24\122\0\1\313"+
    "\74\0\1\235\76\0\1\314\41\0\1\315\126\0\1\235"+
    "\75\0\1\236\60\0\1\316\13\0\1\316\4\0\2\316"+
    "\20\0\6\15\1\0\1\317\2\0\1\15\16\0\1\15"+
    "\1\0\12\15\1\276\1\15\1\277\7\15\12\0\1\15"+
    "\25\0\1\320\51\0\2\244\4\0\1\144\65\0\2\245"+
    "\71\0\6\15\1\0\1\321\2\0\1\15\16\0\1\15"+
    "\1\0\24\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\10\15\1\322\13\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\202\2\0\1\15"+
    "\16\0\1\15\1\0\24\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\20\15"+
    "\1\166\3\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\15\15\1\166\6\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\11\15\1\202\2\15\1\252\7\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\6\15\1\252\15\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\166\2\0\1\15\16\0\1\15"+
    "\1\0\24\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\1\323\23\15\12\0"+
    "\1\15\2\0\6\15\1\0\1\15\2\0\1\15\16\0"+
    "\1\15\1\0\2\15\1\324\21\15\12\0\1\15\2\0"+
    "\6\15\1\0\1\15\2\0\1\15\16\0\1\15\1\0"+
    "\2\15\1\174\4\15\1\325\14\15\12\0\1\15\2\0"+
    "\6\15\1\0\1\171\2\0\1\15\16\0\1\15\1\0"+
    "\24\15\12\0\1\15\2\0\6\15\1\0\1\15\2\0"+
    "\1\15\16\0\1\15\1\0\1\15\1\326\22\15\12\0"+
    "\1\15\2\0\6\15\1\0\1\327\2\0\1\15\16\0"+
    "\1\15\1\0\24\15\12\0\1\15\2\0\6\15\1\0"+
    "\1\15\2\0\1\15\16\0\1\15\1\0\5\15\1\330"+
    "\16\15\12\0\1\15\2\0\6\15\1\0\1\15\2\0"+
    "\1\15\16\0\1\15\1\0\2\15\1\275\21\15\12\0"+
    "\1\15\2\0\6\15\1\0\1\15\2\0\1\15\16\0"+
    "\1\15\1\0\1\331\23\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\1\15"+
    "\1\332\22\15\12\0\1\15\2\0\6\15\1\0\1\262"+
    "\2\0\1\15\16\0\1\15\1\0\24\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\333\2\0\1\15\16\0\1\15"+
    "\1\0\24\15\12\0\1\15\2\0\6\15\1\0\1\201"+
    "\2\0\1\15\16\0\1\15\1\0\24\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\2\15\1\334\21\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\10\15"+
    "\1\203\13\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\12\15\1\335\11\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\6\15\1\334\15\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\7\15\1\336\14\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\3\15"+
    "\1\166\20\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\5\15\1\337\16\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\1\15\1\340\22\15\12\0\1\15"+
    "\2\0\3\15\1\341\2\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\24\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\1\15"+
    "\1\342\22\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\7\15\1\325\14\15"+
    "\12\0\1\15\33\0\1\343\13\0\1\343\4\0\2\343"+
    "\27\0\1\235\73\0\1\344\130\0\1\235\60\0\1\345"+
    "\13\0\1\345\4\0\2\345\20\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\11\15\1\202\12\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\11\15\1\346\12\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\14\15\1\174\7\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\15\15"+
    "\1\202\6\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\2\15\1\202\21\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\12\15\1\347\11\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\5\15\1\350\16\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\7\15"+
    "\1\252\14\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\17\15\1\351\4\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\7\15\1\352\14\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\6\15\1\353\15\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\10\15"+
    "\1\354\13\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\13\15\1\260\10\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\1\15\1\355\22\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\14\15\1\317\7\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\24\15"+
    "\12\0\1\202\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\7\15\1\356\14\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\2\15\1\357\21\15\12\0\1\15\33\0\1\360"+
    "\13\0\1\360\4\0\2\360\55\0\1\361\36\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\3\15"+
    "\1\324\20\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\11\15\1\362\12\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\6\15\1\174\15\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\17\15\1\363\4\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\12\15"+
    "\1\364\11\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\6\15\1\365\15\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\4\15\1\202\17\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\11\15\1\366\12\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\367\2\0\1\15\16\0\1\15\1\0\24\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\23\15\1\370\12\0\1\15\37\0"+
    "\1\235\36\0\6\15\1\0\1\15\2\0\1\15\16\0"+
    "\1\15\1\0\5\15\1\252\16\15\12\0\1\15\2\0"+
    "\6\15\1\0\1\212\2\0\1\15\16\0\1\15\1\0"+
    "\24\15\12\0\1\15\2\0\6\15\1\0\1\15\2\0"+
    "\1\15\16\0\1\15\1\0\10\15\1\371\13\15\12\0"+
    "\1\15\2\0\6\15\1\0\1\15\2\0\1\15\16\0"+
    "\1\202\1\0\24\15\12\0\1\15\2\0\6\15\1\0"+
    "\1\15\2\0\1\15\16\0\1\15\1\0\1\274\23\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\11\15\1\372\12\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\14\15\1\373\7\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\11\15"+
    "\1\166\12\15\12\0\1\15\2\0\6\15\1\0\1\15"+
    "\2\0\1\15\16\0\1\15\1\0\3\15\1\374\20\15"+
    "\12\0\1\15\2\0\6\15\1\0\1\15\2\0\1\15"+
    "\16\0\1\15\1\0\10\15\1\375\13\15\12\0\1\15"+
    "\2\0\6\15\1\0\1\15\2\0\1\15\16\0\1\15"+
    "\1\0\2\15\1\166\21\15\12\0\1\15\2\0\6\15"+
    "\1\0\1\15\2\0\1\15\16\0\1\15\1\0\21\15"+
    "\1\166\2\15\12\0\1\15";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12540];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\1\3\0\1\11\6\1\1\11\1\1\1\11"+
    "\3\1\1\11\1\1\3\11\1\1\1\11\17\1\1\11"+
    "\2\1\4\11\4\1\2\11\6\1\1\11\4\1\1\11"+
    "\23\1\2\11\4\1\2\11\1\1\3\0\3\1\1\11"+
    "\2\1\2\0\45\1\3\11\2\1\5\0\1\11\1\0"+
    "\4\1\1\0\2\1\1\0\10\1\1\11\33\1\3\0"+
    "\2\1\1\11\23\1\1\0\1\11\12\1\1\11\1\0"+
    "\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[253];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 36: 
          { return Tokens.RESERVED_WORD;
          }
        case 45: break;
        case 19: 
          { yybegin(VERB); return Tokens.BRACKET;
          }
        case 46: break;
        case 35: 
          { yybegin(NOUN); return Tokens.FUNCTION;
          }
        case 47: break;
        case 26: 
          { yybegin(YYINITIAL); return Tokens.BAD_CHARACTER;
          }
        case 48: break;
        case 2: 
          { yybegin(YYINITIAL);   return Tokens.BAD_CHARACTER;
          }
        case 49: break;
        case 30: 
          { return Tokens.PARENTHESIS;
          }
        case 50: break;
        case 22: 
          { yybegin(REGULAR_EXPRESSION); return Tokens.REGULAR_EXPRESSION;
          }
        case 51: break;
        case 34: 
          { return Tokens.HEREDOCS;
          }
        case 52: break;
        case 27: 
          { final int length = yytext().length();
        if (length > 1) {
            yypushback(length -1);
            yybegin(REGULAR_EXPRESSION_FLAG);
        } else {
            yybegin(VERB);
        }
        return Tokens.REGULAR_EXPRESSION;
          }
        case 53: break;
        case 42: 
          { yybegin(HEREDOCS); return Tokens.HEREDOCS;
          }
        case 54: break;
        case 25: 
          { return Tokens.REGULAR_EXPRESSION;
          }
        case 55: break;
        case 24: 
          { yybegin(VERB); return Tokens.STRING;
          }
        case 56: break;
        case 14: 
          { yybegin(JAVASCRIPT); return Tokens.JAVASCRIPT;
          }
        case 57: break;
        case 1: 
          { yybegin(VERB); return Tokens.REGULAR_EXPRESSION_FLAG;
          }
        case 58: break;
        case 23: 
          { return Tokens.STRING;
          }
        case 59: break;
        case 43: 
          { yybegin(VERB);  return Tokens.HEREDOCS;
          }
        case 60: break;
        case 39: 
          { return Tokens.BAD_CHARACTER;
          }
        case 61: break;
        case 4: 
          { yybegin(NOUN_OR_VERB); return Tokens.IDENTIFIER;
          }
        case 62: break;
        case 12: 
          { yybegin(NOUN); return Tokens.BRACE;
          }
        case 63: break;
        case 8: 
          { return Tokens.LINE_TERMINATOR;
          }
        case 64: break;
        case 29: 
          { yybegin(NOUN); return Tokens.ASSIGNMENT;
          }
        case 65: break;
        case 33: 
          { yybegin(YYINITIAL); return Tokens.JAVASCRIPT;
          }
        case 66: break;
        case 7: 
          { yybegin(NOUN); return Tokens.ACCESSOR;
          }
        case 67: break;
        case 6: 
          { yybegin(NOUN); return Tokens.OPERATOR;
          }
        case 68: break;
        case 16: 
          { yybegin(VERB); return Tokens.PARENTHESIS;
          }
        case 69: break;
        case 9: 
          { return Tokens.COMMENT;
          }
        case 70: break;
        case 28: 
          { yybegin(NOUN); return Tokens.DOT;
          }
        case 71: break;
        case 41: 
          { return Tokens.REGULAR_EXPRESSION_LITERAL;
          }
        case 72: break;
        case 15: 
          { return Tokens.SEMI_COLON;
          }
        case 73: break;
        case 13: 
          { yybegin(VERB); return Tokens.BRACE;
          }
        case 74: break;
        case 38: 
          { yybegin(VERB); return Tokens.BOOLEAN;
          }
        case 75: break;
        case 21: 
          { yybegin(YYINITIAL); return Tokens.LINE_TERMINATOR;
          }
        case 76: break;
        case 20: 
          { return Tokens.ASSIGNMENT;
          }
        case 77: break;
        case 5: 
          { yybegin(VERB); return Tokens.NUMBER;
          }
        case 78: break;
        case 11: 
          { yybegin(SINGLE_QUOTE_STRING); return Tokens.STRING;
          }
        case 79: break;
        case 37: 
          { yybegin(NOUN); return Tokens.KEYWORD;
          }
        case 80: break;
        case 44: 
          { yybegin(VERB); return Tokens.KEYWORD;
          }
        case 81: break;
        case 18: 
          { yybegin(NOUN); return Tokens.BRACKET;
          }
        case 82: break;
        case 31: 
          { yybegin(NOUN); return Tokens.COMMA;
          }
        case 83: break;
        case 40: 
          { return Tokens.STRING_LITERAL;
          }
        case 84: break;
        case 3: 
          { return Tokens.WHITESPACE;
          }
        case 85: break;
        case 17: 
          { yybegin(NOUN); return Tokens.PARENTHESIS;
          }
        case 86: break;
        case 10: 
          { yybegin(DOUBLE_QUOTE_STRING); return Tokens.STRING;
          }
        case 87: break;
        case 32: 
          { return Tokens.JAVASCRIPT;
          }
        case 88: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
